title = 'Benjamin Vaughn'
baseURL = 'https://benjaminfvaughn.github.io/'
languageCode = 'en-us'
theme = 'ananke'

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Benjamin Vaughn"
    weight = 1
    contentDir = "content"
